package com.myspace.test_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class detail implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Father's Name")
	private java.lang.String father_name;
	@org.kie.api.definition.type.Label(value = "Mother's Name")
	private java.lang.String mother_name;

	public detail() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getFather_name() {
		return this.father_name;
	}

	public void setFather_name(java.lang.String father_name) {
		this.father_name = father_name;
	}

	public java.lang.String getMother_name() {
		return this.mother_name;
	}

	public void setMother_name(java.lang.String mother_name) {
		this.mother_name = mother_name;
	}

	public detail(java.lang.String name, java.lang.String father_name,
			java.lang.String mother_name) {
		this.name = name;
		this.father_name = father_name;
		this.mother_name = mother_name;
	}

}